[build]
builder = "nixpacks"

[build.env]
NIXPACKS_BUILD_DEPS = "php php-cli php-fpm php-mysqlnd php-zip php-mbstring php-xml php-curl php-gd php-intl composer nodejs npm"
NIXPACKS_NODE_VERSION = "18"
NIXPACKS_PHP_VERSION = "8.2"

[deploy]
start = "php artisan serve --host 0.0.0.0 --port $PORT"
