[build]
builder = "nixpacks"

[variables]
APP_ENV="production"
APP_DEBUG="false"
PORT="8080"

[phases.setup]
nixPkgs = [
  "php",
  "php81Extensions.pdo_mysql",
  "php81Extensions.mbstring",
  "php81Extensions.curl",
  "php81Extensions.exif",
  "php81Extensions.fileinfo",
  "php81Extensions.openssl",
  "php81Extensions.dom",
  "php81Extensions.tokenizer",
  "nginx",
  "phpPackages.composer",
  "nodejs_18",
  "npm-9_x"
]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm ci"
]

[phases.build]
cmds = [
  "npm run build",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache",
  "php artisan storage:link"
]

[start]
cmd = "php-fpm8.1 -D && nginx -g 'daemon off;'"
