services:
  - type: web
    name: reporte-alumnos
    env: php
    region: oregon
    buildCommand: |
      composer install --no-dev
      php artisan key:generate
      php artisan migrate --force
    startCommand: |
      php artisan serve --host 0.0.0.0 --port $PORT
    plan: free
    autoDeploy: true

